<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260322151826 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE exploitation DROP FOREIGN KEY `fk_exploitation_user`');
        $this->addSql('ALTER TABLE parcelle DROP FOREIGN KEY `parcelle_ibfk_1`');
        $this->addSql('ALTER TABLE SecurityEvent DROP FOREIGN KEY `securityevent_ibfk_1`');
        $this->addSql('ALTER TABLE UserSession DROP FOREIGN KEY `usersession_ibfk_1`');
        $this->addSql('DROP TABLE activite');
        $this->addSql('DROP TABLE annonce');
        $this->addSql('DROP TABLE cancellation_requests');
        $this->addSql('DROP TABLE commandes');
        $this->addSql('DROP TABLE culture');
        $this->addSql('DROP TABLE delivery_zone');
        $this->addSql('DROP TABLE equipement');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE exploitation');
        $this->addSql('DROP TABLE forum');
        $this->addSql('DROP TABLE ligne_commande');
        $this->addSql('DROP TABLE maintenance');
        $this->addSql('DROP TABLE marketplace_bans');
        $this->addSql('DROP TABLE marketplace_cooldowns');
        $this->addSql('DROP TABLE marketplace_warnings');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE notification_read');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE parcelle');
        $this->addSql('DROP TABLE produits');
        $this->addSql('DROP TABLE SecurityEvent');
        $this->addSql('DROP TABLE UserSession');
        $this->addSql('DROP INDEX idx_user_oauth ON User');
        $this->addSql('DROP INDEX idx_user_active ON User');
        $this->addSql('DROP INDEX idx_fournisseur_numRegistre ON User');
        $this->addSql('DROP INDEX idx_fournisseur_cin ON User');
        $this->addSql('DROP INDEX idx_fournisseur_type ON User');
        $this->addSql('DROP INDEX idx_nom ON User');
        $this->addSql('DROP INDEX idx_is_active ON User');
        $this->addSql('DROP INDEX idx_role ON User');
        $this->addSql('DROP INDEX idx_email ON User');
        $this->addSql('DROP INDEX idx_user_email ON User');
        $this->addSql('ALTER TABLE User MODIFY idUtilisateur INT NOT NULL');
        $this->addSql('ALTER TABLE User ADD roles JSON NOT NULL, ADD phone_number VARCHAR(20) DEFAULT NULL, ADD profile_photo_path VARCHAR(255) DEFAULT NULL, DROP Nom, DROP DateNaissance, DROP telephone, DROP Gouvernant, DROP Ville, DROP CodePostale, DROP role, DROP admin_niveau, DROP agriculteur_expAnnee, DROP agriplus_abonnement, DROP agriplus_dateExpiration, DROP fournisseur_typeFournisseur, DROP fournisseur_certifications, DROP fournisseur_cin, DROP fournisseur_raisonSocial, DROP fournisseur_numRegistre, DROP fournisseur_formeJuridique, DROP fournisseur_capital, DROP email_verified, DROP oauth_provider, DROP oauth_provider_id, DROP password_migrated, DROP failed_login_attempts, DROP locked_until, DROP last_login, DROP email_verification_token, DROP email_verification_expires_at, DROP two_factor_enabled, DROP intrusion_capture_enabled, DROP phone_verified, DROP otp_code, DROP otp_expiration, DROP otp_attempts, DROP face_descriptor, DROP face_enrolled_at, CHANGE Email email VARCHAR(180) NOT NULL, CHANGE is_active is_active TINYINT DEFAULT 1 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE idUtilisateur id INT AUTO_INCREMENT NOT NULL, CHANGE Mdp password VARCHAR(255) NOT NULL, CHANGE PhotoProfil full_name VARCHAR(255) DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE User RENAME INDEX email TO UNIQ_8D93D649E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activite (id_activite INT AUTO_INCREMENT NOT NULL, titre VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, type_activite VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, date_debut DATETIME NOT NULL, date_fin DATETIME DEFAULT NULL, statut VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, cout_estime NUMERIC(10, 2) DEFAULT NULL, id_agriculteur INT NOT NULL, PRIMARY KEY (id_activite)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE annonce (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type VARCHAR(80) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, quantite INT NOT NULL, prixUnitaire DOUBLE PRECISION NOT NULL, status VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, photos TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cancellation_requests (id INT AUTO_INCREMENT NOT NULL, commande_id INT NOT NULL, num_commande VARCHAR(50) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, fournisseur_id INT DEFAULT NULL, requested_by_user_id INT DEFAULT NULL, requested_by_email VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, requested_by_name VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, requested_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, status VARCHAR(20) CHARACTER SET latin1 DEFAULT \'PENDING\' NOT NULL COLLATE `latin1_swedish_ci`, handled_by_user_id INT DEFAULT NULL, handled_at DATETIME DEFAULT NULL, INDEX idx_cr_commande (commande_id), INDEX idx_cr_fournisseur (fournisseur_id), INDEX idx_cr_status (status), PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE commandes (id INT AUTO_INCREMENT NOT NULL, numCommande VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, dateCommande DATE NOT NULL, quantite INT NOT NULL, prixTotal DOUBLE PRECISION NOT NULL, status VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, email VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, prenom VARCHAR(100) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, nom VARCHAR(100) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, adresse VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, complement VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, codePostal VARCHAR(20) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, ville VARCHAR(100) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, telephone VARCHAR(30) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, id_fournisseur INT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE culture (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, type ENUM(\'OLEICULTURE\', \'GRANDES_CULTURES\', \'MARAICHAGE\', \'ARBORICULTURE_FRUITIERE\', \'PHOENICICULTURE\', \'CULTURES_FOURRAGERES\') CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, date_semis DATE DEFAULT NULL, date_recolte DATE DEFAULT NULL, saison ENUM(\'HIVER\', \'PRINTEMPS\', \'ETE\', \'AUTOMNE\') CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, statut ENUM(\'PLANIFIEE\', \'SEMEE\', \'EN_CROISSANCE\', \'EN_RECOLTE\', \'RECOLTEE\', \'ABANDONNEE\') CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, parcelle_id INT NOT NULL, INDEX parcelle_id (parcelle_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE delivery_zone (id BIGINT AUTO_INCREMENT NOT NULL, seller_id BIGINT NOT NULL, city VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, address_label VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, full_address VARCHAR(500) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, max_radius_km DOUBLE PRECISION DEFAULT \'5\' NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX fk_delivery_zone_seller (seller_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE equipement (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, categorie ENUM(\'Véhicule Motorisé\', \'Autre Équipement\') CHARACTER SET utf8mb4 DEFAULT \'Autre Équipement\' NOT NULL COLLATE `utf8mb4_0900_ai_ci`, marque VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, modele VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, date_acquisition DATE DEFAULT NULL, statut ENUM(\'Actif\', \'En panne\', \'En maintenance\', \'Hors service\') CHARACTER SET utf8mb4 DEFAULT \'Actif\' COLLATE `utf8mb4_0900_ai_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, image_url VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, exploitation_id INT DEFAULT NULL, userlog INT DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, date_modification DATETIME DEFAULT NULL, kilometrage_actuel INT DEFAULT 0 COMMENT \'Kilométrage actuel du véhicule\', kilometrage_derniere_maintenance INT DEFAULT 0, seuil_km_maintenance INT DEFAULT 10000 COMMENT \'Maintenance tous les X km\', heures_utilisation INT DEFAULT 0 COMMENT \'Heures d\'\'utilisation\', heures_derniere_maintenance INT DEFAULT 0, seuil_heures_maintenance INT DEFAULT 200 COMMENT \'Maintenance tous les X heures\', seuil_jours_maintenance INT DEFAULT 365 COMMENT \'Maintenance tous les X jours\', date_derniere_maintenance DATE DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evenement (id_evenement INT AUTO_INCREMENT NOT NULL, titre VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, type_evenement VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, date_evenement DATETIME NOT NULL, lieu VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, id_organisateur INT NOT NULL, PRIMARY KEY (id_evenement)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE exploitation (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, ville ENUM(\'TUNIS\', \'ARIANA\', \'BEN_AROUS\', \'MANOUBA\', \'NABEUL\', \'BIZERTE\', \'BEJA\', \'JENDOUBA\', \'LE_KEF\', \'SILIANA\', \'KAIROUAN\', \'KASSERINE\', \'SIDI_BOUZID\', \'SFAX\', \'MAHDIA\', \'MONASTIR\', \'SOUSSE\', \'GABES\', \'MEDENINE\', \'TATAOUINE\', \'GAFSA\', \'TOZEUR\', \'KEBILI\', \'ZAGHOUAN\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, adresse VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, superficie_totale DOUBLE PRECISION DEFAULT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, user_id INT DEFAULT NULL, INDEX fk_exploitation_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE forum (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, categorie VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, user_id INT DEFAULT NULL, INDEX fk_forum_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ligne_commande (id INT AUTO_INCREMENT NOT NULL, id_commande INT NOT NULL, id_produit INT NOT NULL, id_fournisseur INT DEFAULT NULL, nom_produit VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, quantite INT NOT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, prix_total DOUBLE PRECISION NOT NULL, INDEX idx_lc_commande (id_commande), INDEX idx_lc_fournisseur (id_fournisseur), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE maintenance (id INT AUTO_INCREMENT NOT NULL, type ENUM(\'Préventive\', \'Corrective\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, categorie ENUM(\'Régulière\', \'Imprévue\') CHARACTER SET utf8mb4 DEFAULT \'Régulière\' NOT NULL COLLATE `utf8mb4_0900_ai_ci`, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, date_planifiee DATE NOT NULL, date_reelle DATE DEFAULT NULL, statut ENUM(\'Planifiée\', \'En cours\', \'Terminée\', \'Annulée\') CHARACTER SET utf8mb4 DEFAULT \'Planifiée\' COLLATE `utf8mb4_0900_ai_ci`, equipement_id INT NOT NULL, userlog INT DEFAULT NULL, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, declencheur VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'Ex: Kilométrage atteint, Heures atteintes, Panne détectée\', kilometrage_prevu INT DEFAULT NULL COMMENT \'Kilométrage au moment de la maintenance\', heures_prevues INT DEFAULT NULL COMMENT \'Heures au moment de la maintenance\', cout NUMERIC(10, 2) DEFAULT \'0.00\', technicien VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, INDEX equipement_id (equipement_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE marketplace_bans (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, reason VARCHAR(500) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, banned_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, lifted_at DATETIME DEFAULT NULL, appeal_text VARCHAR(1000) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, appeal_at DATETIME DEFAULT NULL, INDEX idx_mb_lifted (lifted_at), INDEX idx_mb_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE marketplace_cooldowns (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, product_id INT DEFAULT NULL, level INT NOT NULL, reason VARCHAR(500) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, start_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, end_at DATETIME NOT NULL, INDEX idx_mc_user (user_id), INDEX idx_mc_end (end_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE marketplace_warnings (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, product_id INT DEFAULT NULL, reason VARCHAR(500) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_mw_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, forum_id INT NOT NULL, user_id INT DEFAULT NULL, contenu TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_envoi DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX forum_id (forum_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notification_read (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, source_type VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, source_id INT NOT NULL, read_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_nr_user (user_id), UNIQUE INDEX uq_notif_read (user_id, source_type, source_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notifications (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, body VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, commande_id INT DEFAULT NULL, read_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, product_id INT DEFAULT NULL, INDEX idx_notif_read (read_at), INDEX idx_notif_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE panier (id INT AUTO_INCREMENT NOT NULL, idPersonne INT DEFAULT NULL, idProduit INT DEFAULT NULL, nomProduit VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, quantite INT NOT NULL, prixTotal DOUBLE PRECISION DEFAULT NULL, dateAjout DATE DEFAULT NULL, INDEX idProduit (idProduit), INDEX idPersonne (idPersonne), PRIMARY KEY (id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE parcelle (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, superficie DOUBLE PRECISION DEFAULT NULL, type_sol ENUM(\'ARGILEUX\', \'SABLONNEUX\', \'LIMONEUX\', \'CAILLOUTEUX\', \'SALIN\') CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, etat ENUM(\'IRRIGUEE\', \'BOUR\', \'PARCOURS\', \'JACHERE\', \'FORESTIERE\') CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, exploitation_id INT NOT NULL, INDEX exploitation_id (exploitation_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE produits (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, categorie VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, prixUnitaire DOUBLE PRECISION NOT NULL, unite_vente VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'kg\' NOT NULL COLLATE `utf8mb4_0900_ai_ci`, image TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, origine VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci`, id_fournisseur INT DEFAULT NULL, description VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, category VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci`, equipement_id INT DEFAULT NULL, culture_id INT DEFAULT NULL, active TINYINT DEFAULT 1 NOT NULL, quantite INT DEFAULT 0 NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_0900_ai_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE SecurityEvent (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, event_type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT, TOKEN_REFRESH, PASSWORD_CHANGE, OAUTH_LOGIN, ACCOUNT_LOCKED, SESSION_REVOKED\', details TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_security_event_time (created_at), INDEX idx_security_event_type (event_type), INDEX idx_security_event_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE UserSession (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, refresh_token_hash VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, device_info VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL, revoked TINYINT DEFAULT 0, INDEX idx_session_token (refresh_token_hash), INDEX idx_session_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE exploitation ADD CONSTRAINT `fk_exploitation_user` FOREIGN KEY (user_id) REFERENCES user (idUtilisateur) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE parcelle ADD CONSTRAINT `parcelle_ibfk_1` FOREIGN KEY (exploitation_id) REFERENCES exploitation (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE SecurityEvent ADD CONSTRAINT `securityevent_ibfk_1` FOREIGN KEY (user_id) REFERENCES user (idUtilisateur) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE UserSession ADD CONSTRAINT `usersession_ibfk_1` FOREIGN KEY (user_id) REFERENCES user (idUtilisateur) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE user MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE user ADD Nom VARCHAR(100) NOT NULL, ADD DateNaissance DATE DEFAULT NULL, ADD PhotoProfil VARCHAR(255) DEFAULT NULL, ADD Gouvernant VARCHAR(100) DEFAULT NULL, ADD Ville VARCHAR(100) DEFAULT NULL, ADD CodePostale VARCHAR(10) DEFAULT NULL, ADD role ENUM(\'ADMIN\', \'AGRICULTEUR\', \'AGRIPLUS\', \'USER\', \'FOURNISSEUR\') DEFAULT \'USER\' NOT NULL, ADD admin_niveau ENUM(\'SUPER_ADMIN\', \'ADMIN\', \'MODERATOR\') DEFAULT NULL, ADD agriculteur_expAnnee INT DEFAULT NULL, ADD agriplus_abonnement ENUM(\'BASIC\', \'PREMIUM\', \'ENTERPRISE\') DEFAULT NULL, ADD agriplus_dateExpiration DATE DEFAULT NULL, ADD fournisseur_typeFournisseur ENUM(\'PERSONNE\', \'SOCIETE\') DEFAULT NULL, ADD fournisseur_certifications TEXT DEFAULT NULL, ADD fournisseur_cin VARCHAR(20) DEFAULT NULL, ADD fournisseur_raisonSocial VARCHAR(200) DEFAULT NULL, ADD fournisseur_numRegistre VARCHAR(50) DEFAULT NULL, ADD fournisseur_formeJuridique VARCHAR(100) DEFAULT NULL, ADD fournisseur_capital NUMERIC(15, 2) DEFAULT NULL, ADD email_verified TINYINT DEFAULT 0, ADD oauth_provider VARCHAR(20) DEFAULT NULL COMMENT \'OAuth provider: google, or NULL for local\', ADD oauth_provider_id VARCHAR(255) DEFAULT NULL COMMENT \'OAuth subject ID from provider\', ADD password_migrated TINYINT DEFAULT 0 COMMENT \'1 = password hashed with BCrypt\', ADD failed_login_attempts INT DEFAULT 0, ADD locked_until DATETIME DEFAULT NULL, ADD last_login DATETIME DEFAULT NULL, ADD email_verification_token VARCHAR(10) DEFAULT NULL, ADD email_verification_expires_at DATETIME DEFAULT NULL, ADD two_factor_enabled TINYINT DEFAULT 0 NOT NULL, ADD intrusion_capture_enabled TINYINT DEFAULT 0 NOT NULL, ADD phone_verified TINYINT DEFAULT 0, ADD otp_code VARCHAR(10) DEFAULT NULL, ADD otp_expiration DATETIME DEFAULT NULL, ADD otp_attempts INT DEFAULT 0, ADD face_descriptor TEXT DEFAULT NULL, ADD face_enrolled_at DATETIME DEFAULT NULL, DROP roles, DROP full_name, DROP profile_photo_path, CHANGE email Email VARCHAR(150) NOT NULL, CHANGE is_active is_active TINYINT DEFAULT 1, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE id idUtilisateur INT AUTO_INCREMENT NOT NULL, CHANGE phone_number telephone VARCHAR(20) DEFAULT NULL, CHANGE password Mdp VARCHAR(255) NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idUtilisateur)');
        $this->addSql('CREATE INDEX idx_user_oauth ON user (oauth_provider, oauth_provider_id)');
        $this->addSql('CREATE INDEX idx_user_active ON user (is_active)');
        $this->addSql('CREATE INDEX idx_fournisseur_numRegistre ON user (fournisseur_numRegistre)');
        $this->addSql('CREATE INDEX idx_fournisseur_cin ON user (fournisseur_cin)');
        $this->addSql('CREATE INDEX idx_fournisseur_type ON user (fournisseur_typeFournisseur)');
        $this->addSql('CREATE INDEX idx_nom ON user (Nom)');
        $this->addSql('CREATE INDEX idx_is_active ON user (is_active)');
        $this->addSql('CREATE INDEX idx_role ON user (role)');
        $this->addSql('CREATE INDEX idx_email ON user (Email)');
        $this->addSql('CREATE INDEX idx_user_email ON user (Email)');
        $this->addSql('ALTER TABLE user RENAME INDEX uniq_8d93d649e7927c74 TO Email');
    }
}
